### ISSUE TITLE
Link bài huớng dẫn trên OSX.vn đã chết

### ISSUE THREAD

**Issue by thanhhaired** [nguyenlc1993/mac-os-k501l#2]
Chào bạn, có vẻ như link bài huớng dẫn trên OSX.vn đã chết mất rồi, bạn có thể cập nhật lại được không ?

**Comment by nguyenlc1993** [comment]
Mình dạo này đang bận nên chưa có thời gian cập nhật guide, bạn tạm thời dùng guide tiếng Anh nhé. Mình sẽ cố gắng đăng lại guide sớm nhất có thể, nhưng sẽ đăng trên forum mới là [weloveapple.vn](http://weloveapple.vn)
