### ISSUE TITLE
K501LB gặp lỗi không chỉnh được độ sáng và ko có âm thanh

### ISSUE THREAD

**Issue by zunsakai** [nguyenlc1993/mac-os-k501l#3]
E cài trên k501LB theo guide của bác, có thanh chỉnh độ sáng nhưng không có tác dụng, và máy ko có âm thanh, đã thử tự patch lại DSDT của máy nhưng có vẻ còn nhiều lỗi hơn @@ đây là DSDT của máy vừa dump từ clover, bác có thời gian thì xem hộ e phải patch những phần gì
[origin.zip](https://github.com/nguyenlc1993/mac-os-k501l/files/1273635/origin.zip)

**Comment by pwn-0x309** [comment]
bạn ơi. bạn làm từng bước ntn? mình boot usb thì bị đơ icon load xoay tròn
